### ISSUE TITLE
Formatting, Grammer and Bugs on the sugar labs website

### ISSUE THREAD

**Issue by dvlasits** [sugarlabs/www-sugarlabs#151]
The main page should not just be grey as a bit boring
The search feature could when highlighted with mouse open a bar and not have to be clicked on to open a new page
On the "use" part it goes to documentation where this sign ¶ appears in red and I don't understand what it does
Formatting changes in the "use" part where I would suggest it should stay the same as the rest of the website
you have an unnecessary comma here: A local Sugar Lab adapts the technology and pedagogy to an area's culture and resources (e.g., developing activities and content specific to a region); after e.g.

**Comment by quozl** [comment]
Thanks for the feedback.  I'll take just one issue; the "use" link.

* it links to https://help.sugarlabs.org/ so any feedback should go to the Help Activity repository, not this repository,
* the red paragraph mark is an anchor reference so you can bookmark it, and is generated by the Help Activity scripting which depends on the Sphinx software, it is supposed to be discoverable rather than documented as to what it does; your surprise is not unexpected, but you were supposed to look at what your browser said about the mark; your browser should have shown the URL to include an anchor (#).
* adopting the main web site theme for this and other sites is indeed something we would like to do.

Also, in future, please use separate GitHub issues for separate problems.  I've only replied to some of the problems.

**Comment by Swayamsvk** [comment]
Can I work on this?

**Comment by quozl** [comment]
Hey Swayam!  Thanks for asking.

This issue was raised by a student during GCI 2017 in contesting for tasks.  GCI is an environment where creativity does not always correlate to forethought.  :grin:

We do not have a consensus among the developers how to respond to this issue.  I've given my opinion, but nobody else has done so.  Therefore it is not, on its own, an important issue.  Think of it as an abandoned unreviewed issue.

Working on this issue as a new developer could be destructive to your reputation in the community. :grin:

The situation with the web site is "abandoned", after years of changes to formatting and style with _no changes_ to content.  We have had discussions in other issues about this; see https://github.com/sugarlabs/www-sugarlabs/issues/305.

If you have skills in HTML5 and JavaScript, you might get involved in the Sugarizer activities or Music Blocks project.

Lastly, our [guide to contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md) says not to ask for permission, but just to make a pull request with your changes.  I'm glad you didn't do that for this issue, 'cause you would have wasted your time.

Because there's no consensus on this issue, and because it has deceived you into thinking it should be fixed, I'll close it now.  Thanks for bringing it to my attention.
