### ISSUE TITLE
Improve of side social buttons style - suggestion [GCI]

### ISSUE THREAD

**Issue by TheLukaszNs** [sugarlabs/www-sugarlabs#171]
I think that these buttons could be styled better - for example adding border-top-[**left/right**]-radius to only first element and border-bottom-[**left/right**]-radius to last one would be much better instead of having one without border radius, next with it and so on.
This: ![gci2](https://user-images.githubusercontent.com/25536472/33676887-47002748-dab7-11e7-9926-f9d9ae8f3bad.png) can look like this: ![gci2 1](https://user-images.githubusercontent.com/25536472/33677227-586d8042-dab8-11e7-98ed-daf4adc5df47.png)

**Comment by Oluebube** [comment]
Am a new contributor can i work on this?

**Comment by kushagra189** [comment]
@TheLukaszNs  is this still up or already assigned?

**Comment by quozl** [comment]
* mostly nobody needs permission to work on anything, just announce if you are working on it, so that your time is not wasted by someone else working on it at the same time,
* asking permission may give no response, as has already happened for @Oluebube, and that doesn't mean much,
* making a pull request to fix a problem that doesn't have wide consensus can stimulate a discussion to achieve that consensus, and that discussion may fail, which then wastes your time.
* it is best to have wide consensus before working on problems of style and design,
* in my opinion, this issue is of no consequence; don't mind if it is fixed, and don't mind if it is not fixed.

**Comment by TheLukaszNs** [comment]
Yeah, as @quozl said - **I'm not the one that allows you to make PR that will resolve this issue**. You can work on any issue you want - it's up to you if you want to contribute!
<hr />
I saw that this issue isn't resolved so far, so go on - do it if You want 😄

**Comment by kanishkarj** [comment]
Hey ! I would like to work on that

**Comment by quozl** [comment]
With ec6074b merged, my opinion is that it looks uglier than before; the eye is drawn to the disparity of the straight browser edge and the unnecessary curve away from the edge.  What do the regular contributors think?

**Comment by kanishkarj** [comment]
How does this look? I tried to cover up that disparity
![screenshot from 2018-03-13 09-35-55](https://user-images.githubusercontent.com/22411349/37322203-3004ab22-26a2-11e8-9134-1f9015c9b826.png)

**Comment by Pro-Panda** [comment]
I agree with @quozl 
I removed the browser edge curve from the social buttons in 06f282c. Does this look better ?
Also, 
 - Sidebar is not visible if the browser window is maximised. It hides if on resizing the window as well [Tested on Firefox 59, Ubuntu 16.04]
 - In my opinion, hovering on an icon should result in a curved corner edge being extended to the right

**Comment by Pro-Panda** [comment]
Looks like @kanishkarj made a similar change simultaneously :grin:

**Comment by kanishkarj** [comment]
Haha yea..
