### ISSUE TITLE
Subscribe button suggestion

### ISSUE THREAD

**Issue by satyamchaudharydev** [sugarlabs/www-sugarlabs#181]
This is how the website looks now:
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/26341752/33803578-7e19e494-ddb9-11e7-98c3-6b01660b62fc.gif)
Color change on hover is too drastic also the width of the input and subscribe button are not same, which doesn't seem right.

Ideally, it should be like that in my opinion.
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/26341752/33803546-ed3e4352-ddb8-11e7-8627-3637af1f3124.gif)

**Comment by lalitmee** [comment]
@satyamchaudharydev Anyone is working on this issue or not?

**Comment by satyamchaudharydev** [comment]
I am working on this issue.

**Comment by octamois** [comment]
@satyamchaudharydev , you still working?
I wish to contribute for this.

**Comment by VatsalBatra** [comment]
@satyamchaudharydev  anyone working on this issue ,if not i wish to take it

**Comment by quozl** [comment]
These comments unrelated to the _problem_ are a distraction.  Please, don't use issues as a place to negotiate who will work on something.  You may get no response.  You may forget to say you've stopped working on it.

Please use a pull request instead.  Check for pull requests linked to the issue; if there are none, then assume nobody has done anything.  Begin to fix the problem, test, [make your commits](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits), push your commits, then [make a pull request](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#sending-a-pull-request).  Mention the issue number in the pull request, but not the commit message.

These practices allow the competition of ideas (via pull requests) instead of competition of observing capability or perceived suitability of a contributor (via issues).

Sugar Labs is a [meritocracy](https://wiki.sugarlabs.org/go/Sugar_Labs).

**Comment by quozl** [comment]
In #243, @yummypasta suggested removing the gap between the entry and the button.

My opinion is that it looks better with the gap; so that the function of each area can be clearly seen.
