### ISSUE TITLE
UI improvement of search box during transition on scrolling

### ISSUE THREAD

**Issue by avinashbharti97** [sugarlabs/www-sugarlabs#205]
As now on scrolling the page navigation-bar content size changes relatively from large to small but the search box remains same

![search3](https://user-images.githubusercontent.com/22724583/37280223-2fda6018-2613-11e8-913c-7f48335d0a28.gif)
 
i think it will look better if the size of seach box also changes relatively something like this

![search2](https://user-images.githubusercontent.com/22724583/37280266-52a8e9a2-2613-11e8-85dc-bd1d019a5aa1.png)

**Comment by kanishkarj** [comment]
Hey Id like to work on this

**Comment by quozl** [comment]
@avinashbharti97.  I don't think it would look better.  Can you explain why you think it would look better?

@kanishkarj.  Please don't.  Wait for consensus.  Working on issues without consensus would waste your time, and there are plenty of other things to do.

**Comment by kanishkarj** [comment]
Okay, sorry..

**Comment by avinashbharti97** [comment]
@quozl  
**If every element of a container have nearly equal padding then it will look  good.**

![after-search](https://user-images.githubusercontent.com/22724583/37339885-281b70f4-26e2-11e8-9831-f1fa5505ae01.jpg)

**But as now padding for sugarlabs logo changes but not for search bar.**

![before-serach](https://user-images.githubusercontent.com/22724583/37339923-4d52b7d8-26e2-11e8-876f-9896243729ea.jpg)


**Also after the scroll search box element starts touching the outer nav container but for element differentiation there should be some padding between parent container and child element.**

**Comment by quozl** [comment]
Good, thanks.  I'll wait for others to assent.

**Comment by AnshulMalik** [comment]
I agree with @avinashbharti97  :)

**Comment by VatsalBatra** [comment]
i would like to work on this one, also i think instead of  just decreasing the size of the search bar, changing the radius of the search bar in sync with transition of navbar would look better

from
![screen shot 2018-03-25 at 4 54 48 am](https://user-images.githubusercontent.com/20797544/37869971-ddc5754e-2fe8-11e8-8a01-927686005747.png)

to

![screen shot 2018-03-25 at 4 47 34 am](https://user-images.githubusercontent.com/20797544/37869973-e72f0794-2fe8-11e8-9bb5-e8986b8948e3.png)

**Comment by quozl** [comment]
Thanks.  However, I'm looking for input from Sugar Labs members; on whether it will look better.  This is a subjective issue.

**Comment by perriefidelis** [comment]
@avinashbharti97 great idea! but if it comes too small it wouldn't look too good. If it's possible to make the search bar as responsive(Just reduce the size on scrolling) as the other element on the nav bar, than that solves the problem better. @VatsalBatra changing the radius if the search bar will distort the uniformity of the site because all other elements are in full rectangles.

**Comment by lakshya-dhariwal** [comment]
Now that the search bar is being mentioned I have noticed that the search icon looks unproportional to the search bar maybe we can also resize it  according to the search bar's size

**Comment by quozl** [comment]
Probably best to look at this after upgrading to latest Bootstrap. #316

**Comment by nikkuAg** [comment]
Hey,
Are you still planning to update the design of serach bar or in navbar, as I am willing to contribute.

**Comment by chimosky** [comment]
> Hey, Are you still planning to update the design of serach bar or in navbar, as I am willing to contribute.

Hi @nikkuAg, yes and you open a PR if you have a fix.
