### ISSUE TITLE
Extreme slowness in page load

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#218]
In a test just now, it took about a minute to finish loading the page, during which the spinner was the only visible element.  Status bar of browser showed resources were being fetched from servers other than sugarlabs.org.

* [ ] while loading, the page should not be hidden by the spinner; interaction must be available as soon as elements are available,
* [ ] all needed resources should be on sugarlabs.org server.

**Comment by VibhorCodecianGupta** [comment]
The website uses CDN for at least jquery and bootstrap among other things, so isn't it inevitable that resources are fetched from other servers?

**Comment by quozl** [comment]
Interesting, thanks.

**Comment by quozl** [comment]
Symptom still occurs.  About a minute.  Most of the time is spent resolving DNS queries and making connections to get resources from off-site.

**Comment by HarrisonLKatz** [comment]
Hello,
I am currently finishing up a somewhat related PR, but one thing I noticed while doing this was how a lot of libraries are out of date. While this might not make a huge difference, it may speed things up to update some of them. For instance, this website is currently using ion icons v2. Ion icons v2 is using a minified css sheet in order to load only 1 resource; however, this causes the sheet to be somewhat large. However, ion icons v4 uses web components instead of a single css sheet. While this means loading more resources, allows it to only load the icons the website uses (which is about 4) instead of loading over 500 different unused icons. The ion icon website claims that this brings a speed improvement, however I have not tested that yet. I don't know if updating any of the other libraries bring any speed improvements, but if there is not a reason for not updating I can try and see if there is any speed improvements by doing so. While this probably would not bring as much speed improvement as the above suggestions, it should help in addition to the above suggestions.
Thank you,
Harrison

**Comment by quozl** [comment]
Thanks.  Yes, many of the resources have not been maintained.  We got security vulnerability warnings from GitHub.  I'm certainly in favour of measurable improvements, and some of what you mention may well be an improvement.  But I'm not in favour of unmeasured improvements.  I've also suggested on sugar-devel@ that the web site be [replaced with a content management system](http://lists.sugarlabs.org/archive/sugar-devel/2018-November/055891.html) with resources that are maintained by others, so we [don't have to spend so much time on it](http://lists.sugarlabs.org/archive/sugar-devel/2018-November/055893.html).
