### ISSUE TITLE
Newsletter subscription redirects to unmanaged or undocumented mailing list

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#249]
Either;

* bring the mailing list in house, using lists.sugarlabs.org, or;
* document the external mailing list for our systems@ infrastructure team.

**Comment by samswag** [comment]
What do you suggest we do like an action plan on these your points?

**Comment by quozl** [comment]
I can't recommend an action plan.  I don't know enough about the feature or intention.  As far as I know, there is no newsletter, nobody is writing it, there is no publishing, and so no need to capture mail addresses yet.  If that situation changes, then do tell me.

**Comment by amaaniqbal** [comment]
Should I create a GCI task to come up with the action plan needed for this purpose? An amazing idea can out from someone. 

Otherwise, I feel it's taking up enough space in the footer and its corresponding code can be commented out at least for now. And we may fill it something useful or redesign the footer itself. Currently, its height is a bit too much in comparison to what a footer's height generally should be.

**Comment by quozl** [comment]
It's not a coding problem.  I don't think a GCI participant could learn enough about Sugar Labs organisation and gain consensus in the time available.

Removing it for now is a good first step, as it stops us lying to visitors.  The footer height is immaterial.

**Comment by amaaniqbal** [comment]
Ya, it's not a coding problem. I am just saying about an action plan. I had created two tasks related to creating a plan for chatbot and another for updating our website to bootstrap 4.1. These prove to be something helpful. Maybe something could come out from this also.

> Removing it for now is a good first step, as it stops us lying to visitors. 

This can be done depending upon consensus.

> The footer height is immaterial.

If we remove the newsletter part, we would have an option to create a new column by taking a few similar rows from the existing columns otherwise it would look as if something is missing on the right side. Also, it would not look organized.

**Comment by quozl** [comment]
I've not seen any action plan for a chatbot or bootstrap, so that kind of task has no benefit to Sugar Labs as far as I can see.  If the action plan was private, what's the point of that?

I'm fine with it not looking organised, as Sugar Labs is not organised.  But I'm also fine with someone changing it to look organised.  It's just that the footer height, the columns, and looking organised is not something I'm interested in collaborating on.

**Comment by amaaniqbal** [comment]
I will send you those plans soon. Walter already has access to them.

**Comment by quozl** [comment]
Why not post to [sugar-devel@ mailing list](http://lists.sugarlabs.org/listinfo/sugar-devel)?

**Comment by amaaniqbal** [comment]
Okay, will do soon.

**Comment by quozl** [comment]
Stale, closing.  There's no newsletter to subscribe to, and nobody is proposing to write one.
