### ISSUE TITLE
"https://owa.kiwiirc.com/piwik.js" responding with error 522

### ISSUE THREAD

**Issue by navanchauhan** [sugarlabs/www-sugarlabs#261]
Possible Fix is to replace "https://owa.kiwiirc.com/piwik.js" with Cloudflare's CDN "https://cdnjs.cloudflare.com/ajax/libs/piwik/3.6.1/piwik.js"

**Comment by quozl** [comment]
Thanks for trying to find the problem, but I've taken what you said and found it's more complicated than that.  What we have now is;
* `js/main.js` changes _myiframe1_ and _myiframe2_ attribute _src_ to an off-site resource,
* that off-site resource then references piwik.js from owa.kiwiirc.com,
* that server doesn't respond for 30 seconds, contributing to #218,
* the reverse proxy in front of owa.kiwiirc.com eventually responds with 522;

```
  HTTP/1.1 522 Origin Connection Time-out
  Date: Tue, 20 Nov 2018 22:04:24 GMT
  Content-Type: text/html; charset=UTF-8
  Content-Length: 4753
  Connection: keep-alive
  Set-Cookie: __cfduid=d12706b47eb0a4f8932128589b9d0ab321542751433; expires=Wed, 20-Nov-19 22:03:53 GMT; path=/; domain=.kiwiirc.com; HttpOnly
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  Set-Cookie: cf_use_ob=0; path=/; expires=Tue, 20-Nov-18 22:04:54 GMT
  Expires: Thu, 01 Jan 1970 00:00:01 GMT
  Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
  Pragma: no-cache
  Server: cloudflare
  CF-RAY: 47ce358abfb8a2ea-HKG
```

This is probably because we shouldn't be using kiwiirc.com in that fashion, and it may be necessary to contact them to figure out how to fix it.  Or even better we could remove kiwiirc.com use until it's fixed.
