### ISSUE TITLE
Purpose of all .sass files?

### ISSUE THREAD

**Issue by HarrisonLKatz** [sugarlabs/www-sugarlabs#262]
Hello,
I am currently working on this website, and could not figure out the purpose of the sass files. I added an import to main, but discovered that main.css is never used on the website. When I imported it, it broke the website. Not only that, but one file, _social.sass, isn't even linked in main.sass. Is there a reason that these are kept, or should I ignore/delete them?
Thank you,
Harrison

**Comment by quozl** [comment]
Thanks.  Interesting.  [SASS](https://en.wikipedia.org/wiki/Sass_(stylesheet_language)) is used by [Jekyll](https://en.wikipedia.org/wiki/Jekyll_(software)).  If someone has changed generated files, i.e. output files that are made from those `.sass` files, then;

* that's all-our fault for letting it happen, because not everyone would have known how Jekyll works, and;
* you can find from `git blame` and other views of history in GitHub why they did it, and ask them.

**Comment by HarrisonLKatz** [comment]
No one has changed the output - I'm just confused because the output is never used. In fact, one of the files does not even output anything. I was wondering if they have any real purpose because I am trying to add some css, and it seems that main.sass outputs main.css which is never imported or used anywhere.

**Comment by quozl** [comment]
Remove the unused files, test that the site still works for you, and make a pull request.  Then anyone who cares about the files will be obliged to give reasons to keep them.

**Comment by HarrisonLKatz** [comment]
Resolved by #263
