### ISSUE TITLE
Sugar title not centered, after removal of the video

### ISSUE THREAD

**Issue by nathan-jacob** [sugarlabs/www-sugarlabs#268]
![image](https://user-images.githubusercontent.com/37455968/48972391-ccadd780-efee-11e8-887c-fff9ff1ee2e5.png)

**Comment by samswag** [comment]
@nathan-jacob want to send a fix?

**Comment by nathan-jacob** [comment]
Sorry, was a bit busy before, here's the fix @samswag

**Comment by samswag** [comment]
Can you just send one PR that fix both issues?

**Comment by quozl** [comment]
Given our [Guide to Reviewers](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#goals) says to _not waste the time of the contributor, by doing anything trivial that otherwise the contributor might have to do_, I tried to identify how to proceed; but was stymied by;
* two pull requests for the same issue; please close any you don't want us to review,
* the second pull request apparently a change subset of the first; please confine your changes to one pull request,
* the commits don't have a good [explanation](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits); please rewrite the commit messages,
* the first pull request has a review comment; please respond.

**Comment by nathan-jacob** [comment]
Pull request aba43c5 does it all in one

**Comment by nathan-jacob** [comment]
https://github.com/sugarlabs/www-sugarlabs/pull/270/files fixes the issue, 
I merged all the pulls into one 

On the html I changed the class name to center because I didn't want it to take on the bootsrap css values

On the css I added a description for class center in order to center .center, that way it wouldnt all by in the middle, but rather, centered.
