### ISSUE TITLE
Sugar Labs logo size

### ISSUE THREAD

**Issue by Gabbar8055** [sugarlabs/www-sugarlabs#278]
The size of sugar labs logo looks stretched on large-size devices.
![22](https://user-images.githubusercontent.com/39026182/49688653-3a88f180-fb0d-11e8-8f86-0f7c735e00b2.PNG)
The size of sugar labs logo on medium-size devices is getting out of navigation bar.
![21](https://user-images.githubusercontent.com/39026182/49688677-905d9980-fb0d-11e8-983d-597a30a435ec.PNG)

**Comment by quozl** [comment]
Unable to reproduce.  Tested Firefox on Ubuntu 16.04, and Firefox and Safari on iPad with iOS 12.  The logo correctly appears on Firefox and does not look stretched.  The logo does not appear on Safari.

Please provide browser, operating system, and display resolution details.

**Comment by aryanharitsh123** [comment]
@quozl Yes, it is working fine on Ubuntu 18.04 too, tried Firefox and Chrome. Display resolutions are
1366x768 and 1920x1080.

**Comment by quozl** [comment]
@Gabbar8055, which version of Chrome?

**Comment by quozl** [comment]
Thanks.  Reproduced on Chrome 71.0.3578.80 on Ubuntu 16.04 by shrinking the window in various ways.  About 800x600 yields a thinner logo.  About 600x800 yields logo over navigation area.  But it all still works; what is the problem with the size changes of the logo?

**Comment by Gabbar8055** [comment]
I think it would look better if the logo does not come out of the navigation bar in 600x800 resolution and also a little bit less thin in 800x600 resolution. What do you think @quozl ?

**Comment by quozl** [comment]
Thanks.  I don't think it matters.  Our critical problem is with content, not presentation.  Visitors are not staying on the page for very long, and they don't learn what we do.  I'll ask again; what is the problem with the size changes of the logo?  You've said it would look better; but how would it look better?

@sugarlabs/a-b

**Comment by Gabbar8055** [comment]
Thanks for review the issue. If you think the presentation does not matter that much then its OK! and there is no problem with the size changes of the logo. The issue is only about the presentation of the logo.

**Comment by MastaCoder** [comment]
I have managed to reproduce this.

When the page is loaded with a large format, a green icon is shown. Dynamically changing the size of the window down to a point where it goes into dropdown mode causes the logo to grow outside of the navigation bar. However, loading the page in a smaller format, an orange logo is shown instead. Changing the size of the window then has the logo grow and shrink properly.

An easy fix is to retain the orange logo no matter what size screen on page load, or to use the same logo resizing CSS with the green logo as well. Right now, the green logo has a fixed size no matter what size, that's why it falls off the navigation bar.

**Comment by quozl** [comment]
Wouldn't it be easier to bring in the upstream changes to the theme or undo changes to the theme that were made since it was last brought in from upstream?

**Comment by quozl** [comment]
Stale, closing.
