### ISSUE TITLE
How to rebuild the website?

### ISSUE THREAD

**Issue by rahul-bothra** [sugarlabs/www-sugarlabs#333]
I recently pushed to master 2a40dfb. I was hoping that the site would rebuild on it's own, but it did not.

Is something broken?

**Comment by chimosky** [comment]
There was a conversation on something similar a while ago but I can't remember where it was, I think it was on the devel list but maybe @srevinsaju can help.

**Comment by srevinsaju** [comment]
For some background regarding this:

The `www-sugarlabs` is hosted on freedom, it was moved to freedom to ease the building of the website by non-shell account holders using a github webhook kafka queue.

As of now.. the kafka queue and the www-rebuilder container is completely broken ¯\_(ツ)_/¯ and I have no idea how to fix the rebuilder (its something written in python, but I do not have enough resources to debug it).. It was initially written by Sam Parkinson.. 

So, on sugar-devel@ I proposed two ideas:

* Moving the website back to sunjammer 
* Hosting the `www-sugarlabs` website on github pages.

Hosting it on github pages with a custom domain, pointing the `CNAME` to `sugarlabs.github.io` would help to show the website on `www.sugarlabs.org`. I like this idea, because:
* It will help reduce some maintenance.
* The website would be instantly built without delay due to the powerful Jekyll builder provided by GitHub.
* Contributors would have more flexible access to the building technollogy

If we would like to go with `www.sugarlabs.org` on github `gh-pages`, then:

* The built website will look like this [g.srev.in/www-sugarlabs/](http://g.srev.in/www-sugarlabs/) (sample)
* Would require giving me maintainer access to [www-sugarlabs](https://github.com/sugarlabs/www-sugarlabs) github repository, so that I can edit the DNS records and update the settings to build the website using github jekyll builder, (alternatively, being online on [#sugar:matrix.org](https://app.element.io/#/room/#sugar:matrix.org) on a scheduled time would help me coordinate the DNS changes to this repository, but that would require a synchronous conversation, as we had done on [developer.sugarlabs.org](https://developer.sugarlabs.org/sugar3/) but that was me and quozl doing the important changes.


If hosting it on [sunjammer](https://sunjammer.sugarlabs.org) is the thing, then:
* create a new tooling to listen to webhooks to replace, the old kafka `www-rebuilder`
* Host it on sunjammer
* Profit! :tada:

**Comment by rahul-bothra** [comment]
Thanks, moving discussion to #332
