### ISSUE TITLE
Source map errors

### ISSUE THREAD

**Issue by quozl** [sugarlabs/www-sugarlabs#357]
No impact, but Firefox browser tools says

```
Source map error: Error: request failed with status 404
Resource URL: http://www.sugarlabs.org/css/bootstrap.css
Source Map URL: bootstrap.css.map
```

**Comment by S-kus** [comment]
When I am migrating it from bootstrap v3 to v4 in https://github.com/sugarlabs/www-sugarlabs/pull/347 I found out it's happening because of commented link in `bootstrap.css` in line **8975** i.e. last line. 
We can solve it by adding the **bootstrap.css.map** file from official documents of Bootstrap v4 in the same CSS folder.
Can I raise the pr by adding the file? Do I need to update the Licence file also?

**Comment by quozl** [comment]
> When I am migrating it from bootstrap v3 to v4 in #347 I found out it's happening because of commented link in `bootstrap.css` in line **8975** i.e. last line. We can solve it by adding the **bootstrap.css.map** file from official documents of Bootstrap v4 in the same CSS folder.

Thanks.  Fixed.

> Can I raise the pr by adding the file?

I'm tired of being asked.  It's about time you read our guide to [Contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md) in particular where it starts out saying

> "_Please note there is no need to ask permission to work on an issue. You should check for pull requests linked to an issue you are addressing; if there are none, then assume nobody has done anything. Begin to fix the problem, test, make your commits, push your commits, then make a pull request. Mention an issue number in the pull request, but not the commit message. These practices allow the competition of ideas (Sugar Labs is a meritocracy)._"

:grin:

> Do I need to update the Licence file also?

Nothing about the license file needs to change, does it?

**Comment by S-kus** [comment]
> Nothing about the license file needs to change, does it?

No, Sorry! I misunderstood.
