### ISSUE TITLE
Revamping the New Sugar Site

### ISSUE THREAD

**Issue by EmilyOng** [sugarlabs/www-sugarlabs#61]
![screen shot 2017-01-08 at 12 23 47 am](https://cloud.githubusercontent.com/assets/21200681/21743227/d474d0f4-d538-11e6-9c54-3973c527c71c.png)

The social media icons are too small and are placed at the footer [_includes/footer.html], which makes it easily missed by the audiences. They are not visible enough, so perhaps there could be an icon in place, or make the icons/words larger. There could also be an embedded Twitter/Facebook timeline on the page as well.

**Comment by samswag** [comment]
Great idea Emily..

**Comment by EmilyOng** [comment]
It may be able to improve marketing and publicity for Sugar

**Comment by samswag** [comment]
Can you look into it?

**Comment by EmilyOng** [comment]
Sure

**Comment by EmilyOng** [comment]
https://emilyong.github.io/sugar-web/

**Comment by samswag** [comment]
Great..nice. i just viewed it on my phone.. i will look into it on my
macbook.

**Comment by EmilyOng** [comment]
Thanks... i will have to resize the twitter feed as it is way too "long".
Im missing a footer with copyright infos plus i am thinking of adding some
kind of "slider" or bs carousel that shows users' reviews about
activities/sugar

**Comment by samswag** [comment]
Can you draw inspiration from this! this is our proposed plan for the site. https://github.com/sugarlabs/www-sugarlabs/blob/master/STRUCTURE.md

This is how we intend to see or even do better! 

http://haxe.org

https://learningequality.org

Can i have your personal mail, so that we can work on this together! But i like your proposed plan! Fantastic with the pop-up thingy!

**Comment by EmilyOng** [comment]
No problem :)

**Comment by EmilyOng** [comment]
https://github.com/sugarlabs/www-sugarlabs/blob/master/STRUCTURE.md#conversion-funnel

**Comment by EmilyOng** [comment]
hmm i dont really understand the conversion funnel and my impression is:

there is a homepage. like the links that you have provided, probably it will be nice for it to kind of "fit to screen". so when you open up the website, there is like this one background.

in the middle, there will be buttons for the conversion funnel (probably this is how we use it) and when we hover over the buttons, there will be tooltips on what it is about. clicking on a button will have this scroll effect. we can link them using ahref and a name. lets say we click on button a, it will scroll the page down to the content of a. is this what u mean?

**Comment by EmilyOng** [comment]
> there is a homepage. like the links that you have provided, probably it will be nice for it to kind of "fit to screen". so when you open up the website, there is like this one background.

probably like learningquality.org

**Comment by samswag** [comment]
I dont really know much! But you can ask Dave Crossland, he proposed the
site.

On 16 Jan 2017 9:36 a.m., "Emily Ong" <notifications@github.com> wrote:

hmm i dont really understand the conversion funnel and my impression is:

there is a homepage. like the links that you have provided, probably it
will be nice for it to kind of "fit to screen". so when you open up the
website, there is like this one background.

in the middle, there will be buttons for the conversion funnel (probably
this is how we use it) and when we hover over the buttons, there will be
tooltips on what it is about. clicking on a button will have this scroll
effect. we can link them using ahref and a name. lets say we click on
button a, it will scroll the page down to the content of a. is this what u
mean?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sugarlabs/www-sugarlabs/issues/61#issuecomment-272801666>,
or mute the thread

**Comment by samswag** [comment]
I prefer the other site when it comes to the headings and features.

**Comment by EmilyOng** [comment]
@davelab6 i dont really agree with https://github.com/sugarlabs/www-sugarlabs/blob/master/STRUCTURE.md#tertiary-elements . having them at the footer means lesser exposure and  outreach

**Comment by EmilyOng** [comment]
> I prefer the other site when it comes to the headings and features.

yes, i do agree as well! :smile:

**Comment by EmilyOng** [comment]
btw does sugar have this official instagram account: sugarlabsforall? what if we include a chat box in our website?

**Comment by samswag** [comment]
Yes! That is the official instagram. Can we chat via irc?

On 16 Jan 2017 9:59 a.m., "Emily Ong" <notifications@github.com> wrote:

btw does sugar have this official instagram account: sugarlabsforall? what
if we include a chat box in our website?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sugarlabs/www-sugarlabs/issues/61#issuecomment-272805752>,
or mute the thread

**Comment by EmilyOng** [comment]
No problem. I have followed you on twitter. @emilyo11_

**Comment by davelab6** [comment]
Emily, i checked your github quickly and looking at https://emilyong.github.io you sefini

**Comment by davelab6** [comment]
Emily, i checked your github quickly and looking at https://emilyong.github.io you definitely have the practical web design skills to develop the site. If you disagree with anything that I propose on the structure doc, I am happy for you to implement what you think is best :) 

A conversion funnel is actually an abstract concept and doesn't manifest directly on the oage. It is instead an "information architecture" rather than a concrete "interaction design." I suggest to do some background googling on the difference between the two :)

**Comment by EmilyOng** [comment]
https://gist.github.com/EmilyOng/4b09c9d396856ced7e6e2b8f1eea06c0
emilyong.github.io/sugar-web
its supposed to look like this: but github.io is not showing it well.

![screen shot 2017-01-20 at 10 21 35 pm](https://cloud.githubusercontent.com/assets/21200681/22152776/56059790-df5f-11e6-82ef-721e5410ca60.png)
![screen shot 2017-01-20 at 10 24 27 pm](https://cloud.githubusercontent.com/assets/21200681/22152770/556724fc-df5f-11e6-8f5a-2e806e06de98.png)
![screen shot 2017-01-20 at 10 24 32 pm](https://cloud.githubusercontent.com/assets/21200681/22152769/55533834-df5f-11e6-858a-79b25c8dda91.png)
![screen shot 2017-01-20 at 10 24 40 pm](https://cloud.githubusercontent.com/assets/21200681/22152772/5576eb3a-df5f-11e6-961f-c4b1baed399b.png)
![screen shot 2017-01-20 at 10 24 49 pm](https://cloud.githubusercontent.com/assets/21200681/22152773/5577451c-df5f-11e6-8736-855202c187db.png)
![screen shot 2017-01-20 at 10 24 56 pm](https://cloud.githubusercontent.com/assets/21200681/22152771/55768fbe-df5f-11e6-987d-b7c5a63bca81.png)
![screen shot 2017-01-20 at 10 25 04 pm](https://cloud.githubusercontent.com/assets/21200681/22152774/558b39e6-df5f-11e6-9e2d-fe466b43f63c.png)
![screen shot 2017-01-20 at 10 25 07 pm](https://cloud.githubusercontent.com/assets/21200681/22152775/55a1dc28-df5f-11e6-9ae9-f745c60e7b39.png)

**Comment by EmilyOng** [comment]
i cant seem to load the designs for w3.css buttons (learn more, download, try it now), image gallery, and everything seems jumbled up and messy. the page is not divided into two columns in the parts where i have indicated it to be.

**Comment by EmilyOng** [comment]
its all right, solved the careless problem. but the w3 css tool doesnt appear?

**Comment by samswag** [comment]
I will look into it.


Samson Goddy

**Comment by EmilyOng** [comment]
All right, thank you. But how is it?

**Comment by samswag** [comment]
Nice concept, but low colours

**Comment by EmilyOng** [comment]
Oh...what about colors for each section like previously?

**Comment by samswag** [comment]
Yeah. But not the exact colours, we can come up with something else.

**Comment by EmilyOng** [comment]
what does this mean?
> "Learning To Change The World" full text liberated

**Comment by quozl** [comment]
@EmilyOng, it may have something to do with a book by @walterbender, _Learning to Change the World_, published in 2012.  Full text may imply either an e-book or the text only.  Liberated may mean a licensing change.  You might ask who wrote that; `git blame` says it came from @davelab6 in 812e3690b362fa263e18d1f06948216e.

**Comment by walterbender** [comment]
Emily, Dave asked me to ask my publisher to let us publish the book on line for free access. I've not heard back yet. But we can by the laws of fair use publish the Sugar chapter (See http://people.sugarlabs.org/walter/docs/Learning-to-Change-the-World-Chapter-4.pdf) already.

**Comment by EmilyOng** [comment]
![screen shot 2017-01-27 at 10 32 21 pm](https://cloud.githubusercontent.com/assets/21200681/22374312/b0806566-e4e0-11e6-9741-7c4f4653e691.png)
![screen shot 2017-01-27 at 10 32 44 pm](https://cloud.githubusercontent.com/assets/21200681/22374316/b083aea6-e4e0-11e6-8c68-758b639ddd00.png)
![screen shot 2017-01-27 at 10 32 51 pm](https://cloud.githubusercontent.com/assets/21200681/22374311/b07f10bc-e4e0-11e6-8316-111195c03e11.png)
![screen shot 2017-01-27 at 10 32 57 pm](https://cloud.githubusercontent.com/assets/21200681/22374313/b081af66-e4e0-11e6-981c-c58111a46eae.png)
![screen shot 2017-01-27 at 10 33 01 pm](https://cloud.githubusercontent.com/assets/21200681/22374315/b082c36a-e4e0-11e6-955c-4cdca72e603d.png)
![screen shot 2017-01-27 at 10 33 12 pm](https://cloud.githubusercontent.com/assets/21200681/22374314/b081ff48-e4e0-11e6-8271-3efff0156d49.png)
![screen shot 2017-01-27 at 10 33 18 pm](https://cloud.githubusercontent.com/assets/21200681/22374318/b0b0d908-e4e0-11e6-9a10-503072a1fcf2.png)
![screen shot 2017-01-27 at 10 33 23 pm](https://cloud.githubusercontent.com/assets/21200681/22374317/b0af10aa-e4e0-11e6-8816-f429ac253a77.png)
![screen shot 2017-01-27 at 10 33 31 pm](https://cloud.githubusercontent.com/assets/21200681/22374319/b0b2b0ac-e4e0-11e6-99a8-dd834031ed34.png)
![screen shot 2017-01-27 at 10 33 40 pm](https://cloud.githubusercontent.com/assets/21200681/22374320/b0b374ba-e4e0-11e6-93da-1ef9a7928c6f.png)

apparently there seems to be some problem with emilyong.github.io/sugar-web ...

**Comment by EmilyOng** [comment]
im actually quite confused with:
1. the navigation bar should appear as red but it doesnt
2. the sugarlabsbg.jpeg doesnt show up as a background image for web in the first part
3. i wonder if pdfs embed are actually compatible across devices
4. it kinda got messed up on my phone 😢

**Comment by davelab6** [comment]
Use the chrome Web inspector to debug 🏁

**Comment by EmilyOng** [comment]
Is the concept fine?

**Comment by EmilyOng** [comment]
2(index):1 Mixed Content: The page at 'https://emilyong.github.io/sugar-web/' was loaded over HTTPS, but requested an insecure plugin resource 'http://people.sugarlabs.org/walter/docs/Learning-to-Change-the-World-Chapter-4.pdf'. This request has been blocked; the content must be served over HTTPS.
https://emilyong.github.io/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 Mixed Content: The page at 'https://emilyong.github.io/sugar-web/' was loaded over HTTPS, but requested an insecure plugin resource 'http://people.sugarlabs.org/walter/docs/Learning-to-Change-the-World-Chapter-4.pdf'. This request has been blocked; the content must be served over HTTPS.
